/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        Client client = new Client();
        client.startClient();
    }
}
