/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sethpthomas91.server;

import java.net.Inet4Address;
import java.net.UnknownHostException;

public class App {

    public static void main(String[] args) throws Exception {
        ServerSocketWrapper serverSocket = new ServerSocketWrapper(5050);
        Server server = new Server(serverSocket);
        server.startServer();
    }

}
